---
mysql_root_password: "password123"
mysql_db_name: "php_mysql_crud"
mysql_host: "192.168.56.222"
app_user: "vagrant"
http_host: "localhost"
http_conf: "localhost.conf"
http_port: "80"
disable_default: true